FROM dalongrong/openresty:bashible as build
WORKDIR /opt
COPY content/ /opt/content
RUN cd /opt/content/ && bashible t.bash

FROM openresty/openresty:alpine
COPY --from=build /usr/local/openresty/nginx/html/index.html  /usr/local/openresty/nginx/html/index.html